import Link from "next/link";
import { APPLE_MUSIC, AUDIOMACK, INSTAGRAM, catalog } from "../lib/site";

const frames=[
 {src:"/brick-portrait.webp",label:"PORTRAIT / DAYLIGHT",alt:"KNALEDGE550 portrait against a weathered brick wall"},
 {src:"/phone-candid.webp",label:"CANDID / DAYLIGHT",alt:"KNALEDGE550 candid portrait during a phone call"},
 {src:"/driveway-1.webp",label:"NIGHT / DRIVEWAY",alt:"KNALEDGE550 nighttime documentary portrait"}
];

export default function Home(){return <main className="noirPage">
<header className="noirNav"><a className="noirBrand" href="#top">KNALEDGE550</a><nav aria-label="Primary navigation"><a href="#era">THE ACRONYM</a><a href="#music">MUSIC</a><a href="#world">550 WORLD</a><a href="#artist">ARTIST</a><Link href="/epk">EPK</Link></nav></header>
<section id="top" className="noirHero"><video autoPlay muted loop playsInline preload="metadata" poster="/hero-poster.webp" aria-hidden="true"><source src="/hero-red-mirror-optimized.mp4" type="video/mp4"/></video><div className="noirHeroCopy"><span className="eyebrow">OFFICIAL ARTIST SITE · CURRENT ERA</span><h1>KNALEDGE<span>550</span></h1><p>Music, motion and the world behind the artist. Enter the current era through <strong>The Acronym</strong>.</p><div className="noirActions"><a className="noirBtn primary" href={APPLE_MUSIC} target="_blank" rel="noreferrer">LISTEN NOW ↗</a><a className="noirBtn" href="#era">EXPLORE THE ERA ↓</a></div></div></section>
<section id="era" className="noirSection era"><div className="eraMedia"><video autoPlay muted loop playsInline preload="metadata" poster="/bridge-poster.webp"><source src="/bridge-video.mp4" type="video/mp4"/></video><span>550 · CURRENT ERA</span></div><div className="eraCopy"><span className="eyebrow">FEATURED PROJECT</span><h2>THE<br/>ACRONYM</h2><p>The current KNALEDGE550 chapter. Start with the project, then move deeper into the catalog and visual world.</p><div className="noirActions"><Link className="noirBtn primary" href="/releases/the-acronym">OPEN RELEASE →</Link><a className="noirBtn" href={AUDIOMACK} target="_blank" rel="noreferrer">AUDIOMACK ↗</a></div></div></section>
<section id="music" className="noirSection"><div className="sectionHead"><div><span className="eyebrow">01 · DISCOGRAPHY</span><h2>MUSIC</h2></div><p>Projects and singles from KNALEDGE550. Open a release or continue to an official streaming destination.</p></div><div className="musicRail">{catalog.map((r)=><Link key={r.slug} className="releaseTile" href={`/releases/${r.slug}`}><small>{r.code} · {r.type}</small><strong>{r.title}</strong></Link>)}</div><div className="noirActions"><a className="noirBtn primary" href={APPLE_MUSIC} target="_blank" rel="noreferrer">APPLE MUSIC ↗</a><a className="noirBtn" href={AUDIOMACK} target="_blank" rel="noreferrer">AUDIOMACK ↗</a></div></section>
<section className="watch" aria-label="KNALEDGE550 motion"><video autoPlay muted loop playsInline preload="metadata" poster="/bw-poster.webp"><source src="/bw-closeup.mp4" type="video/mp4"/></video><div className="watchCopy"><span className="eyebrow">02 · MOTION</span><h2>WATCH.</h2></div></section>
<section id="world" className="noirSection"><div className="sectionHead"><div><span className="eyebrow">03 · SELECTED FRAMES</span><h2>550 WORLD</h2></div><p>Documentary photographs and visual fragments from the world surrounding the music.</p></div><div className="visualGrid">{frames.map((f,i)=><figure key={f.src}><img src={f.src} loading="lazy" alt={f.alt}/><figcaption>FRAME 00{i+1} · {f.label}</figcaption></figure>)}</div></section>
<section id="artist" className="noirSection artist"><div><img src="/bw-back.webp" loading="lazy" alt="Black-and-white KNALEDGE550 archival portrait"/></div><div className="artistCopy"><span className="eyebrow">04 · THE ARTIST</span><h2>KNALEDGE<br/>550</h2><p>The official destination for KNALEDGE550 brings the music, selected visuals, current releases and approved press material together without separating the artist from the world around the work.</p><div className="noirActions"><Link className="noirBtn primary" href="/epk">OPEN EPK →</Link><a className="noirBtn" href={INSTAGRAM} target="_blank" rel="noreferrer">INSTAGRAM ↗</a></div></div></section>
<footer className="noirFooter"><span className="eyebrow">OFFICIAL ARTIST DESTINATION</span><strong>KNALEDGE550</strong><div className="footerLinks"><a href={APPLE_MUSIC} target="_blank" rel="noreferrer">APPLE MUSIC</a><a href={AUDIOMACK} target="_blank" rel="noreferrer">AUDIOMACK</a><a href={INSTAGRAM} target="_blank" rel="noreferrer">INSTAGRAM</a><Link href="/epk">PRESS / EPK</Link><span>© 2026 KNALEDGE550</span></div></footer>
</main>}
