"use client";
import Link from "next/link";
import {useEffect,useRef,useState} from "react";
import {APPLE_MUSIC,AUDIOMACK,INSTAGRAM,catalog} from "../lib/site";
const frames=[{src:"/brick-portrait.webp",label:"PORTRAIT / DAYLIGHT",alt:"KNALEDGE550 portrait against a weathered brick wall"},{src:"/phone-candid.webp",label:"CANDID / DAYLIGHT",alt:"KNALEDGE550 candid portrait during a phone call"},{src:"/driveway-1.webp",label:"NIGHT / DRIVEWAY",alt:"KNALEDGE550 nighttime documentary portrait"}];
const art=["/brick-portrait.webp","/phone-candid.webp","/driveway-1.webp","/driveway-2.webp","/bw-back.webp","/hero-poster.webp"];
export default function Home(){const hero=useRef(null);const [progress,setProgress]=useState(0);const [heroP,setHeroP]=useState(0);useEffect(()=>{const reduced=matchMedia("(prefers-reduced-motion: reduce)").matches;const reveal=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add("isVisible")}),{threshold:.08});document.querySelectorAll("[data-reveal]").forEach(el=>reveal.observe(el));let raf=0;const tick=()=>{raf=0;const max=document.documentElement.scrollHeight-innerHeight;setProgress(max?scrollY/max:0);if(hero.current&&!reduced){const r=hero.current.getBoundingClientRect();setHeroP(Math.max(0,Math.min(1,-r.top/Math.max(1,r.height-innerHeight))))}};const onScroll=()=>{if(!raf)raf=requestAnimationFrame(tick)};tick();addEventListener("scroll",onScroll,{passive:true});return()=>{reveal.disconnect();removeEventListener("scroll",onScroll);if(raf)cancelAnimationFrame(raf)}} ,[]);return <main className="noirPage">
<header className="noirNav"><a className="noirBrand" href="#top">KNALEDGE550</a><nav aria-label="Primary navigation"><a href="#era">THE ACRONYM</a><a href="#music">MUSIC</a><a href="#world">550 WORLD</a><a href="#artist">ARTIST</a><Link href="/epk">EPK</Link></nav></header>
<section id="top" ref={hero} className="heroStage" style={{"--hero-p":heroP}}><div className="heroSticky"><div className="heroFilm"><video autoPlay muted loop playsInline preload="auto" poster="/hero-poster.webp" aria-hidden="true"><source src="/hero-red-mirror-optimized.mp4" type="video/mp4"/></video><div className="heroFrame"/></div><div className="noirHeroCopy"><span className="eyebrow">THE ACRONYM · CURRENT ERA</span><h1>KNALEDGE550</h1><div className="heroReveal"><h2>THE ACRONYM</h2><a className="noirBtn primary" href={APPLE_MUSIC} target="_blank" rel="noreferrer">LISTEN NOW ↗</a></div></div></div></section>
<section id="era" className="noirSection era" data-reveal><div className="eraMedia"><video muted loop playsInline preload="metadata" poster="/bridge-poster.webp" onCanPlay={e=>e.currentTarget.play().catch(()=>{})}><source src="/bridge-video.mp4" type="video/mp4"/></video><span>550 · CURRENT ERA</span></div><div className="eraCopy"><span className="eyebrow">FEATURED PROJECT</span><h2><span>THE</span> ACRONYM</h2><p>The current KNALEDGE550 chapter. Start with the project, then move deeper into the catalog and visual world.</p><div className="noirActions"><Link className="noirBtn primary" href="/releases/the-acronym">VIEW RELEASE →</Link><a className="textLink" href={AUDIOMACK} target="_blank" rel="noreferrer">STREAM PROJECT ↗</a></div></div></section>
<section id="music" className="noirSection musicSection"><div className="sectionHead" data-reveal><div><span className="eyebrow">01 · DISCOGRAPHY</span><h2>MUSIC</h2></div><p>Projects and singles from KNALEDGE550. Swipe the catalog or open a release.</p></div><div className="musicGallery">{catalog.map((r,i)=><Link key={r.slug} className={`releaseCard ${r.featured?"featured":r.type==="PROJECT"?"project":"single"}`} href={`/releases/${r.slug}`} data-reveal><img src={art[i%art.length]} loading="lazy" alt=""/><span className="releaseShade"/><div className="releaseMeta"><small>{String(i+1).padStart(2,"0")} / {String(catalog.length).padStart(2,"0")} · {r.type}</small><strong>{r.title}</strong><span>OPEN ↗</span></div></Link>)}</div><div className="catalogLinks"><a href={APPLE_MUSIC} target="_blank" rel="noreferrer">APPLE MUSIC ↗</a><a href={AUDIOMACK} target="_blank" rel="noreferrer">AUDIOMACK ↗</a></div></section>
<section className="watch" aria-label="KNALEDGE550 motion" data-reveal><div className="watchCopy"><span className="eyebrow">02 · MOTION</span><h2>WATCH.</h2></div><div className="watchMedia"><video muted loop playsInline preload="metadata" poster="/bw-poster.webp" onCanPlay={e=>e.currentTarget.play().catch(()=>{})}><source src="/bw-closeup.mp4" type="video/mp4"/></video><span className="playMark">MOTION / 550 · PLAY ↗</span></div></section>
<section id="world" className="noirSection"><div className="sectionHead" data-reveal><div><span className="eyebrow">03 · SELECTED FRAMES</span><h2>550 WORLD</h2></div><p>Documentary photographs and visual fragments from the world surrounding the music.</p></div><div className="visualGrid">{frames.map((f,i)=><figure key={f.src} data-reveal><div className="worldMedia"><img src={f.src} loading="lazy" alt={f.alt}/></div><figcaption>FRAME 00{i+1} · {f.label}</figcaption></figure>)}</div></section>
<section id="artist" className="noirSection artist" data-reveal><div className="artistMedia"><img src="/bw-back.webp" loading="lazy" alt="Black-and-white KNALEDGE550 archival portrait"/></div><div className="artistCopy"><span className="eyebrow">04 · THE ARTIST</span><h2>KNALEDGE550</h2><p>The official destination for KNALEDGE550 brings the music, selected visuals, current releases and approved press material together without separating the artist from the world around the work.</p><div className="noirActions"><Link className="noirBtn primary" href="/epk">OPEN EPK →</Link><a className="textLink" href={INSTAGRAM} target="_blank" rel="noreferrer">INSTAGRAM ↗</a></div></div></section>
<footer className="noirFooter"><span className="eyebrow">OFFICIAL ARTIST DESTINATION</span><strong>KNALEDGE550</strong><div className="footerLinks"><a href={APPLE_MUSIC} target="_blank" rel="noreferrer">APPLE MUSIC</a><a href={AUDIOMACK} target="_blank" rel="noreferrer">AUDIOMACK</a><a href={INSTAGRAM} target="_blank" rel="noreferrer">INSTAGRAM</a><Link href="/epk">PRESS / EPK</Link><span>© 2026 KNALEDGE550</span></div></footer>
<a className="stickyListen" href={APPLE_MUSIC} target="_blank" rel="noreferrer"><span>THE ACRONYM</span><b>LISTEN ↗</b><i aria-hidden="true" style={{transform:`scaleX(${progress})`}}/></a></main>}
